field: a955b2d3-60ee-4dcb-8f3b-f1b3aef05893 # Page Content
fieldLayouts:
  153b245a-fa8f-4220-a466-33bdd9f41720:
    tabs:
      -
        elements:
          -
            fieldUid: e95eb7a9-0dc9-4fbc-b127-96f956cbe14e # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  e95eb7a9-0dc9-4fbc-b127-96f956cbe14e: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:d32ee691-cade-4bed-ab28-97461af96d11' # Site Assets
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:d32ee691-cade-4bed-ab28-97461af96d11' # Site Assets
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: image
name: Image
sortOrder: 2
