fieldLayouts:
  6678243f-8a2b-48d7-bf71-03f7b1ee0f0b:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: contactForm
hasTitleField: false
name: 'Contact Us'
section: 13e92352-ca92-4db4-aa5b-69b2504bfcb0 # Contact Us
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
