columnSuffix: null
contentColumnType: string
fieldGroup: 9983c9f1-f187-4b1c-b28d-84e91bc6627d # Work
handle: image
instructions: ''
name: Image
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:d32ee691-cade-4bed-ab28-97461af96d11' # Site Assets
  defaultUploadLocationSubpath: /paintings
  limit: ''
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:d32ee691-cade-4bed-ab28-97461af96d11' # Site Assets
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
