columnSuffix: null
contentColumnType: text
fieldGroup: 9983c9f1-f187-4b1c-b28d-84e91bc6627d # Work
handle: notes
instructions: ''
name: Notes
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
