columnSuffix: null
contentColumnType: string
fieldGroup: 3af3b2dd-a774-4ea1-9f92-c98cfaa3d1e6 # Common
handle: pageContent
instructions: 'Matrix field for generic page content.'
name: 'Page Content'
searchable: false
settings:
  contentTable: '{{%matrixcontent_pagecontent}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
