columnSuffix: null
handle: text
instructions: null
name: 'Page Content - Text - Text'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  columnType: text
  css: null
  cssFile: null
  defaultTransform: ''
  fullGraphqlData: false
  headingLevels:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
  js: null
  jsFile: null
  options: null
  purifierConfig: ''
  purifyHtml: '1'
  showUnpermittedFiles: ''
  showUnpermittedVolumes: ''
  toolbar:
    - heading
    - '|'
    - bold
    - italic
    - link
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
