columnSuffix: null
contentColumnType: text
fieldGroup: 9983c9f1-f187-4b1c-b28d-84e91bc6627d # Work
handle: year
instructions: ''
name: Year
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
