dateModified: 1783021392
email:
  fromEmail: info@edvinsstrautmanisart.com
  fromName: 'Edvins Strautmanis Art'
  replyToEmail: null
  template: null
  transportSettings:
    host: smtp.zoho.com
    password: en3Factah1Wedge!
    port: '587'
    useAuthentication: '1'
    username: info@edvinsstrautmanisart.com
  transportType: craft\mail\transportadapters\Smtp
fs:
  paintings:
    hasUrls: true
    name: Paintings
    settings:
      path: /var/www/edvinsstrautmanisart.com/web/assets/paintings
    type: craft\fs\Local
    url: '@webroot/assets/paintings'
  siteAssets:
    hasUrls: true
    name: 'Site Assets'
    settings:
      path: /var/www/edvinsstrautmanisart.com/web/assets
    type: craft\fs\Local
    url: //edvinsstrautmanisart.com/assets
meta:
  __names__:
    1b31ea90-ae44-49ed-8e11-953acd5449c8: Category # Category
    1b90fc58-6fb7-49aa-840c-ca336c59833a: 'Optimized Images' # Optimized Images
    6b1c07bc-2f79-41d4-8cfd-faf0a21382c4: Image # Image
    7d4c7977-cd8d-4bda-92b3-cef519b1c389: Work # Work
    10bf254c-f11e-41a7-bc5c-25794fd826cc: 'Edvins Strautmanis Art' # Edvins Strautmanis Art
    11f6a896-fc06-4d68-92c6-27bef538e4a3: Pages # Pages
    13e92352-ca92-4db4-aa5b-69b2504bfcb0: 'Contact Us' # Contact Us
    16ebf092-cb35-4d3a-8e99-d7d441a12f71: New # New
    38b23a9d-00da-4029-8b23-ad8a7db99391: 'Big Thumb' # Big Thumb
    66a55a9d-71ea-4c99-a19f-72fbba755e52: Work # Work
    92b9648b-9d74-4877-b379-b885622d0a06: Thumb # Thumb
    97c731cf-c3f7-4a80-ae6f-203982b035ed: 'Contact Us' # Contact Us
    316e79be-3f1e-45b4-ad64-553353e5abc4: Notes # Notes
    373e57fd-8b25-4bda-a891-5a8e39c00669: 'Edvins Strautmanis Art' # Edvins Strautmanis Art
    6682d502-8e26-4c8c-8d49-347ba76eeeeb: Home # Home
    18252c25-8d55-4941-bc7b-71c03a3d0372: Size # Size
    39111da2-ccb6-45d7-abae-c353a6e1b2c4: About # About
    83887eb1-4ce1-461b-a2d8-5b72d7cd8eb0: Home # Home
    3954844c-6fbc-40ef-a444-452507d1881a: sixxfour # sixxfour
    4930256a-a90d-47b7-8884-05151924bc2a: 'Public Schema' # Public Schema
    a955b2d3-60ee-4dcb-8f3b-f1b3aef05893: 'Page Content' # Page Content
    afd26d5c-5d99-4270-bbb1-300f0c9f8c8e: Year # Year
    b3d7c48e-857b-4b01-b594-5334932d5fb9: Paintings # Paintings
    b24a58d0-641a-49db-baf0-aa04cbcfbda8: Medium # Medium
    cc5b8db8-d1b2-464b-ad1c-08e5aadd72d0: Work # Work
    d1b4dfd7-357d-4c22-8833-c08cfd6ddabb: About # About
    d32ee691-cade-4bed-ab28-97461af96d11: 'Site Assets' # Site Assets
    dc4f5604-2387-421e-a11b-8035fd08f095: Medium(640w) # Medium(640w)
    e00f1be3-1fff-49af-81ca-5e24f21f84de: 'Square Thumb' # Square Thumb
    e943be92-d528-4d31-93c5-4e85d47cb76f: Featured # Featured
    e27591a4-219b-4d25-b9ec-54f0af397f11: Description # Description
    eba44438-976e-43a8-a4a9-28f86f22c6c2: 'Page Content - Text - Text' # Page Content - Text - Text
    ec6a5247-8cc6-4adf-ae21-d904992a802d: Pages # Pages
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 5.6.0.0
  expanded-singles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  formie:
    edition: standard
    enabled: true
    licenseKey: WKOQD375H01U32VYSC9844X2
    schemaVersion: 3.4.12
    settings:
      ajaxTimeout: 10
      alertEmails: null
      allowPublicVolumes: true
      captchas:
        __assoc__:
          -
            - akismet
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\Akismet
                -
                  - enabled
                  - '0'
                -
                  - saveSpam
                  - true
                -
                  - settings
                  -
                    __assoc__:
                      -
                        - handle
                        - akismet
          -
            - captchaEu
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\CaptchaEu
                -
                  - enabled
                  - '0'
                -
                  - saveSpam
                  - true
                -
                  - settings
                  -
                    __assoc__:
                      0:
                        - handle
                        - captchaEu
                      3:
                        - endPoint
                        - 'https://www.captcha.eu'
          -
            - cleantalk
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\CleanTalk
                -
                  - enabled
                  - '0'
                -
                  - saveSpam
                  - true
                -
                  - settings
                  -
                    __assoc__:
                      -
                        - handle
                        - cleantalk
          -
            - turnstile
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\Turnstile
                -
                  - enabled
                  - '0'
                -
                  - saveSpam
                  - true
                -
                  - settings
                  -
                    __assoc__:
                      0:
                        - handle
                        - turnstile
                      3:
                        - scriptLoadingMethod
                        - asyncDefer
                      4:
                        - theme
                        - auto
                      5:
                        - size
                        - normal
                      6:
                        - appearance
                        - always
          -
            - duplicate
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\Duplicate
                -
                  - enabled
                  - '0'
                -
                  - saveSpam
                  - true
                -
                  - settings
                  -
                    __assoc__:
                      -
                        - handle
                        - duplicate
          -
            - friendlyCaptcha
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\FriendlyCaptcha
                -
                  - enabled
                  - '0'
                -
                  - saveSpam
                  - true
                -
                  - settings
                  -
                    __assoc__:
                      0:
                        - handle
                        - friendlyCaptcha
                      3:
                        - apiVersion
                        - v1
                      4:
                        - language
                        - en
                      5:
                        - startMode
                        - none
          -
            - hcaptcha
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\Hcaptcha
                -
                  - enabled
                  - '0'
                -
                  - saveSpam
                  - true
                -
                  - settings
                  -
                    __assoc__:
                      0:
                        - handle
                        - hcaptcha
                      3:
                        - size
                        - normal
                      4:
                        - theme
                        - light
                      5:
                        - language
                        - en
                      6:
                        - minScore
                        - 0.5
                      7:
                        - scriptLoadingMethod
                        - asyncDefer
          -
            - honeypot
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\Honeypot
                -
                  - enabled
                  - '0'
                -
                  - saveSpam
                  - true
                -
                  - settings
                  -
                    __assoc__:
                      -
                        - handle
                        - honeypot
          -
            - javascript
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\Javascript
                -
                  - enabled
                  - '0'
                -
                  - saveSpam
                  - true
                -
                  - settings
                  -
                    __assoc__:
                      -
                        - handle
                        - javascript
          -
            - OopSpam
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\OopSpam
                -
                  - enabled
                  - '0'
                -
                  - saveSpam
                  - true
                -
                  - settings
                  -
                    __assoc__:
                      -
                        - handle
                        - OopSpam
          -
            - question
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\Question
                -
                  - enabled
                  - '0'
                -
                  - saveSpam
                  - true
                -
                  - settings
                  -
                    __assoc__:
                      -
                        - handle
                        - question
          -
            - recaptcha
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\Recaptcha
                -
                  - enabled
                  - '1'
                -
                  - saveSpam
                  - true
                -
                  - settings
                  -
                    __assoc__:
                      -
                        - handle
                        - recaptcha
                      -
                        - secretKey
                        - 6LcTe-oqAAAAAF2AlcSdBi3USjkZgTig0fGCaxJG
                      -
                        - siteKey
                        - 6LcTe-oqAAAAAAJT3ki3MSdSL4z5U19VE4uBump8
                      -
                        - type
                        - v3
                      -
                        - size
                        - normal
                      -
                        - theme
                        - light
                      -
                        - badge
                        - bottomright
                      -
                        - language
                        - en
                      -
                        - minScore
                        - 0.5
                      -
                        - scriptLoadingMethod
                        - asyncDefer
                      -
                        - enterpriseType
                        - score
      defaultDateDisplayType: calendar
      defaultDateTime: null
      defaultDateValueOption: ''
      defaultEmailTemplate: ''
      defaultExportFolder: '@storage/formie-export'
      defaultFileUploadVolume: ''
      defaultFormTemplate: ''
      defaultInstructionsPosition: verbb\formie\positions\AboveInput
      defaultLabelPosition: verbb\formie\positions\AboveInput
      defaultPage: forms
      emptyValuePlaceholder: 'No response.'
      enableBackSubmission: true
      enableCsrfValidationForGuests: true
      enableLargeFieldStorage: false
      enableUnloadWarning: true
      filterIntegrationMapping: true
      includeDraftElementUsage: false
      includeRevisionElementUsage: false
      maxIncompleteSubmissionAge: 30
      maxSentNotificationsAge: 30
      outputConsoleMessages: true
      pdfPaperOrientation: portrait
      pdfPaperSize: letter
      pluginName: Formie
      queuePriority: null
      saveSpam: true
      sendEmailAlerts: false
      sentNotifications: true
      setOnlyCurrentPagePayload: false
      spamBehaviour: showSuccess
      spamBehaviourMessage: ''
      spamEmailNotifications: false
      spamKeywords: ''
      spamLimit: 500
      submissionSidebarFormOrder: dateCreatedDesc
      submissionsBehaviour: all
      useCssLayers: false
      useQueueForIntegrations: true
      useQueueForNotifications: true
      validateCustomTemplates: true
  image-optimize:
    edition: standard
    enabled: true
    licenseKey: 1QJED8T2H3B54LH7TV74QPEP
    schemaVersion: 1.0.0
    settings:
      allowUpScaledImageVariants: false
      assetVolumeSubFolders: true
      autoSharpenScaledImages: true
      capSilhouetteSvgSize: true
      createColorPalette: false
      createPlaceholderSilhouettes: false
      imageTransformTypeSettings:
        __assoc__:
          -
            - nystudio107\imageoptimizeimgix\imagetransforms\ImgixImageTransform
            -
              __assoc__:
                -
                  - domain
                  - ''
                -
                  - apiKey
                  - ''
                -
                  - securityToken
                  - ''
                -
                  - unsharpMask
                  - '20'
          -
            - nystudio107\imageoptimizesharp\imagetransforms\SharpImageTransform
            -
              __assoc__:
                -
                  - baseUrl
                  - ''
          -
            - nystudio107\imageoptimizethumbor\imagetransforms\ThumborImageTransform
            -
              __assoc__:
                -
                  - baseUrl
                  - ''
                -
                  - securityKey
                  - ''
      lowerQualityRetinaImageVariants: true
      sharpenScaledImagePercentage: 50
      transformClass: nystudio107\imageoptimize\imagetransforms\CraftImageTransform
  seomatic:
    edition: standard
    enabled: true
    licenseKey: 277YHPMN3B31SN7Q1BCJFQER
    schemaVersion: 3.0.13
    settings:
      addHrefLang: true
      addPaginatedHreflang: true
      addXDefaultHrefLang: true
      alwaysIncludeCanonicalUrls: false
      cpTitlePrefix: '⚙ '
      cspNonce: ''
      cspScriptSrcPolicies:
        -
          __assoc__:
            -
              - policy
              - "'self'"
      devModeCpTitlePrefix: ''
      devModeTitlePrefix: ''
      displayAnalysisSidebar: true
      displayPreviewSidebar: true
      enableJsonLdEndpoint: false
      enableMetaContainerEndpoint: false
      enableSeoFileLinkEndpoint: false
      environment: live
      excludeNonCanonicalUrls: false
      generatorEnabled: false
      headersEnabled: true
      includeHomepageInBreadcrumbs: true
      lowercaseCanonicalUrl: true
      manuallySetEnvironment: false
      maxDescriptionLength: 155
      maxTitleLength: 70
      metaCacheDuration: 0
      pluginName: SEO
      regenerateSitemapsAutomatically: true
      renderEnabled: true
      separatorChar: '|'
      sidebarDisplayPreviewTypes:
        - google
        - facebook
      siteGroupsSeparate: '1'
      siteUrlOverride: ''
      sitemapsEnabled: true
      socialMediaPreviewTarget: true
      submitSitemaps: true
      truncateDescriptionTags: '1'
      truncateTitleTags: '1'
  sidebar-admin-links:
    edition: standard
    enabled: false
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'Edvins Strautmanis Art'
  retryDuration: null
  schemaVersion: 5.10.0.0
  timeZone: America/New_York
users:
  allowPublicRegistration: false
  deactivateByDefault: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
