defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  373e57fd-8b25-4bda-a891-5a8e39c00669: # Edvins Strautmanis Art
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
