defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 6682d502-8e26-4c8c-8d49-347ba76eeeeb # Home
handle: home
maxAuthors: 1
minAuthors: 1
name: Home
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  373e57fd-8b25-4bda-a891-5a8e39c00669: # Edvins Strautmanis Art
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
