defaultPlacement: end
enableVersioning: true
handle: work
name: Work
propagationMethod: all
siteSettings:
  373e57fd-8b25-4bda-a891-5a8e39c00669: # Edvins Strautmanis Art
    enabledByDefault: true
    hasUrls: true
    template: work/_entry
    uriFormat: 'work/{slug}'
type: channel
